package com.reflex.model.enums;

public enum TaskDifficulty {
    JUNIOR_BEGINNER, JUNIOR_INTERMEDIATE, JUNIOR_ADVANCED, MIDDLE_BEGINNER, MIDDLE_INTERMEDIATE,
    MIDDLE_ADVANCED, SENIOR_BEGINNER, SENIOR_INTERMEDIATE, SENIOR_ADVANCED
}
